"""v10.2 support console tables

Revision ID: 46cbe50493ce
Revises: 765f4874c82b
Create Date: 2026-07-18 09:26:34.445804
"""
from alembic import op
import sqlalchemy as sa


revision = '46cbe50493ce'
down_revision = '765f4874c82b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_number', sa.String(length=64), nullable=False),
    sa.Column('admin_user', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('msg_type', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=255), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_messages_created', 'admin_messages', ['created_at'], unique=False)
    op.create_index('idx_admin_messages_wa', 'admin_messages', ['wa_number'], unique=False)
    op.create_index('idx_admin_messages_wamid', 'admin_messages', ['wa_message_id'], unique=False)
    op.create_table('conversation_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_number', sa.String(length=64), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('assigned_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_number')
    )
    op.create_table('conversation_settings',
    sa.Column('wa_number', sa.String(length=64), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('wa_number')
    )
    op.create_table('internal_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_number', sa.String(length=64), nullable=False),
    sa.Column('admin_user', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_internal_notes_wa', 'internal_notes', ['wa_number'], unique=False)
    op.create_table('message_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('wa_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_status_wa', 'message_status', ['wa_number'], unique=False)
    op.create_index('idx_message_status_wamid', 'message_status', ['wa_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_status_wamid', table_name='message_status')
    op.drop_index('idx_message_status_wa', table_name='message_status')
    op.drop_table('message_status')
    op.drop_index('idx_internal_notes_wa', table_name='internal_notes')
    op.drop_table('internal_notes')
    op.drop_table('conversation_settings')
    op.drop_table('conversation_assignments')
    op.drop_index('idx_admin_messages_wamid', table_name='admin_messages')
    op.drop_index('idx_admin_messages_wa', table_name='admin_messages')
    op.drop_index('idx_admin_messages_created', table_name='admin_messages')
    op.drop_table('admin_messages')
    # ### end Alembic commands ###
